# Macro file for NobleG4.
#
# Can be run in batch, without graphic
# or interactively: Idle> /control/execute run1.mac

# Initialize kernel.
/run/initialize

# Set the verbosity.
/control/verbose 1
/run/verbose 1
/event/verbose 0
/tracking/verbose 0

# Set the impinging particle type and energy.
/gun/particle e-
/gun/energy 1 MeV

# Set the secondary production cuts.
/run/setCut 0.001 mm

# Start the run.
/run/beamOn 1000
